version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "pip"
    directory: "/sdk/python"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "npm"
    directory: "/sdk/typescript"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "typescript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "docker"
