apiVersion: v1
entries:
  ginger:
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2026-07-06T14:44:58.187265196Z"
    description: OpenTelemetry tracing toolkit for Kubernetes with post-quantum cryptography
    digest: edadefebc174ef73f3f8b42393089995abc67f685443b92a1bc4612f6a963c8f
    maintainers:
    - name: Asymmetric Effort
      url: https://github.com/asymmetric-effort
    name: ginger
    type: application
    urls:
    - https://ginger.asymmetric-effort.com/helm/ginger-0.0.4.tgz
    version: 0.0.4
generated: "2026-07-06T14:44:58.186622781Z"
